services:
  - type: web
    name: truestate-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 22.13.1
      - key: PORT
        value: 5000
      - key: TURSO_DATABASE_URL
        sync: false
      - key: TURSO_AUTH_TOKEN
        sync: false
      - key: CSV_FILE_PATH
        value: ./truestate_assignment_dataset.csv
